version: "3.9"

services:
  backend:
    build:
      context: .                # Use project root
      dockerfile: backend/Dockerfile
    container_name: privdesk-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: privdesk-db
    environment:
      POSTGRES_USER: privdesk_user
      POSTGRES_PASSWORD: privdesk_pass
      POSTGRES_DB: privdesk_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
    container_name: privdesk-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
