name: Build & Deploy PrivDesk

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file for backend
        run: echo "${{ secrets.BACKEND_ENV }}" > backend/.env

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Set up Docker Compose
        run: docker compose --version

      - name: Build and start all services
        run: docker compose up -d --build

      - name: Wait for backend to start
        run: |
          echo "Waiting for backend..."
          sleep 10

      - name: Check frontend build exists
        run: test -f frontend/dist/index.html

      - name: Stop containers
        run: docker compose down
