name: Build & Deploy PrivDesk

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          docker compose --version

      - name: Build and start all services
        run: docker compose up -d --build

      - name: Wait for backend to start
        run: |
          echo "Waiting for FastAPI backend..."
          sleep 10  # optionally replace with a curl health check

      - name: Check frontend build exists
        run: test -f frontend/dist/index.html || echo "⚠️ Build not found!"

      - name: Stop containers
        run: docker compose down
