name: Reset Dev DB on Fly (Manual)

on:
  workflow_dispatch:

jobs:
  reset-db:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Run reset script on Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          fly ssh console -a privdesk-app -C "python3 app/scripts/dev_reset.py"
