name: Reset Dev DB (Manual)

on:
  workflow_dispatch:

jobs:
  reset-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Run reset script on Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl ssh console -a privdesk-app -C "python3 /app/app/scripts/dev_reset.py"
