name: Build & Deploy PrivDesk Frontend

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      # Build & deploy using the Dockerfile in /frontend, ignoring cache
      - name: Deploy to Fly.io (no cache, tagged)
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy \
            --config fly.toml \
            --remote-only \
            --no-cache \
            --image-label ${{ github.sha }} \
            --app ${{ secrets.FRONTEND_FLY_APP_NAME }}